### ISSUE TITLE
BLAS doesn't seem to support 64-bit integers

### ISSUE THREAD

**Issue by ghost** [sdsc/octave-roll#1]
Hi after installing SDSC roll I tried to make this roll on Rocks 6.2. I received the following build error:

configure: error: BLAS doesn't seem to support 64-bit integers.  This is incompatible with --enable-64.
make[5]: **\* [build] Error 1
make[5]: Leaving directory `/root/build/octave-roll/BUILD/sdsc-octave-4.0.0'
make[4]: *** [build] Error 2
make[4]: Leaving directory`/root/build/octave-roll/BUILD/sdsc-octave-4.0.0'
error: Bad exit status from /var/tmp/rpm-tmp.6ecPDS (%build)

**Comment by jjhayes** [comment]
Thanks for the report.  We'll have a look to see if we can track down the problem.

Jim

**Comment by jjhayes** [comment]
I did some work in the octave-roll without encountering this message, which makes me think that it might be an issue with the CentOS blas packages.  You can either remove the --enable-64 option from the octave Makefile, or try installing the MKL libraries (see the intel-roll doc) before rebuilding.

Thanks,
Jim

**Comment by kbgith** [comment]
I have the same problem as zeber19.

```
checking whether the integer size is correct... no
configure: error: BLAS doesn't seem to support 64-bit integers.  This is incompatible with --enable-64.
```

I removed all previous CentOS installations of BLAS.

Could we please reopen this issue?

**Comment by jjhayes** [comment]
I'm still unable to recreate this.  Do you have the 64-bit MKL libraries installed?

Jim

**Comment by kbgith** [comment]
These are AMD processors, so I don't have any Intel MKL installed.
But when installing BLAS, and other packages, I did select the 64-bit versions.

**Comment by jjhayes** [comment]
Just merged a change that allows the roll to build with the system BLAS and LAPACK libraries.  It will still use the MKL libraries if they're available, but they're no longer required.

Jim
